# Set up terraform pathing
export PATH="/workspace/.tfenv/bin:$PATH"

# Set up terragrunt pathing
export PATH="/workspace/.tgenv/bin:$PATH"

# Set up prompt
PS1="[\u \W]\\$ "

# Set up kubeswitch
source /usr/local/bin/switch.sh
